// Operational execution of the generated deliverable.
//
// Parsing a generated YAML or JSON file proves it is well formed, not that it
// works. The generated workflow bodies previously ran `npm test --prefix
// tools/compiler` — valid YAML naming a path retired with the duplicate
// compiler, so the generated tree shipped a job that could not execute
// anywhere. These tests RUN the generated commands in an isolated generated
// tree and fail on any that is structurally valid but operationally dead.
import assert from 'node:assert/strict';
import test from 'node:test';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { parse as parseYaml } from 'yaml';

import { loadManifest } from '../semantic-model-compilation/manifest.mjs';
import { loadAuthorityDataset } from '../semantic-model-compilation/authority-dataset.mjs';
import { generateAuthority } from './artefact-generation.mjs';
import { GENERATED_OUTPUT_ROOT } from './generated-output-validation/index.mjs';

const REPOSITORY_ROOT = join(import.meta.dirname, '..', '..');

// Retired topology that must not survive anywhere in the generated bytes.
const RETIRED_REFERENCES = [
  'tools/compiler',
  'tools/validation/validate-graph.sh',
  'v2/usf',
  'graph/manifest.yaml',
];

function generateInto() {
  const container = mkdtempSync(join(tmpdir(), 'usf-generated-command-'));
  const dataset = loadAuthorityDataset(loadManifest(join(REPOSITORY_ROOT, 'semantic-model')));
  // No signing key: the determinate projections are unaffected and the release
  // integrity chain is reported unresolved, which is exactly the surface these
  // command tests need.
  const result = generateAuthority({ store: dataset.store, outputDir: join(container, 'tree'), mode: 'full' });
  return { container, root: result.outputDir, result };
}

// The generated tree's own `node --test` run must report as it would in the
// workflow that ships with it. This process is itself a Node test runner, and
// NODE_TEST_CONTEXT leaks into descendants and switches their reporter off TAP
// onto an IPC channel that does not exist here, so a working generated command
// would look silent and broken. Node deliberately propagates active permission
// flags to Node children even when NODE_OPTIONS is removed; callers add only
// the exact runtime reads their child command needs.
function childEnvironment() {
  const environment = { ...process.env };
  delete environment.NODE_TEST_CONTEXT;
  delete environment.NODE_OPTIONS;
  return environment;
}

function generatedFiles(root, accumulated = []) {
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const path = join(root, entry.name);
    if (entry.isDirectory()) generatedFiles(path, accumulated);
    else accumulated.push(path);
  }
  return accumulated;
}

test('no generated byte references retired repository topology', () => {
  const { container, root } = generateInto();
  try {
    const offending = [];
    for (const path of generatedFiles(root)) {
      const text = readFileSync(path, 'utf8');
      for (const reference of RETIRED_REFERENCES) {
        if (text.includes(reference)) offending.push({ path: path.slice(root.length + 1), reference });
      }
    }
    assert.deepEqual(offending, [], 'generated output still names retired topology');
  } finally {
    rmSync(container, { recursive: true, force: true });
  }
});

test('generated package scripts, test command and evidence pipeline execute', () => {
  const { container, root } = generateInto();
  const generated = join(root, GENERATED_OUTPUT_ROOT);
  try {
    const packagePath = join(generated, 'source/package.json');
    assert.ok(existsSync(packagePath), 'generated source/package.json is absent');
    const manifest = JSON.parse(readFileSync(packagePath, 'utf8'));
    assert.ok(manifest.scripts?.test, 'generated package declares no test script');

    // The generated test command actually runs, in the generated tree.
    const npmRoot = join(dirname(process.execPath), '..', 'lib/node_modules/npm');
    const npmCli = join(npmRoot, 'bin/npm-cli.js');
    const testOutput = execFileSync(process.execPath, [
      '--permission',
      '--allow-child-process',
      `--allow-fs-read=${npmRoot}`,
      `--allow-fs-read=${generated}`,
      npmCli,
      'test',
      '--prefix',
      'source',
    ], {
      cwd: generated,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
      env: childEnvironment(),
    });
    assert.match(testOutput, /# pass 1/);
    assert.doesNotMatch(testOutput, /# fail [1-9]/);

    // Every module the generated tree references must resolve from where it
    // ships, not only exist as text.
    const obligations = join(generated, 'source/implementation-obligations.mjs');
    const pipeline = join(generated, 'assurance/proof/evidence-pipeline.mjs');
    assert.ok(existsSync(obligations) && existsSync(pipeline));
    execFileSync(process.execPath, ['--input-type=module', '-e',
      `import obligations from ${JSON.stringify(obligations)}; if (!Array.isArray(obligations) || obligations.length === 0) throw new Error('empty');`,
    ], { stdio: 'pipe', env: childEnvironment() });
  } finally {
    rmSync(container, { recursive: true, force: true });
  }
});

test('the generated evidence pipeline reports the exact release-integrity state', () => {
  const { container, root } = generateInto();
  const generated = join(root, GENERATED_OUTPUT_ROOT);
  try {
    // Generated without a signing key, so the release manifest is absent and the
    // pipeline must fail loudly rather than report success over nothing.
    assert.equal(existsSync(join(generated, 'release/manifest.json')), false);
    assert.throws(() => execFileSync(process.execPath, ['assurance/proof/evidence-pipeline.mjs', 'verify'], {
      cwd: generated,
      stdio: 'pipe',
      env: childEnvironment(),
    }));
  } finally {
    rmSync(container, { recursive: true, force: true });
  }
});

test('every generated workflow body names commands that exist in the tree it ships with', () => {
  const { container, root } = generateInto();
  const generated = join(root, GENERATED_OUTPUT_ROOT);
  try {
    const workflows = generatedFiles(generated)
      .filter((path) => /\/automation\/[^/]*\.yaml$/.test(path));
    assert.ok(workflows.length > 0, 'no generated workflow was produced');

    for (const path of workflows) {
      const document = parseYaml(readFileSync(path, 'utf8'));
      const steps = Object.values(document.jobs ?? {}).flatMap((job) => job.steps ?? []);
      const commands = steps.map((step) => step.run).filter(Boolean);
      assert.ok(commands.length > 0, `${path} declares no run step`);
      for (const command of commands) {
        // Every `--prefix <dir>` must name a directory that ships in the tree,
        // and every npm script must be declared by that directory's package.
        const prefix = /--prefix\s+(\S+)/.exec(command)?.[1];
        if (!prefix) continue;
        const prefixed = join(generated, prefix);
        assert.ok(existsSync(join(prefixed, 'package.json')), `${command} names an absent package: ${prefix}`);
        const scripts = JSON.parse(readFileSync(join(prefixed, 'package.json'), 'utf8')).scripts ?? {};
        const script = /npm (?:run\s+--prefix\s+\S+\s+|test\s+--prefix\s+\S+)\s*(\S*)/.exec(command);
        const name = command.includes('npm test') ? 'test' : script?.[1];
        assert.ok(name && scripts[name], `${command} names an undeclared script: ${name}`);
      }
    }
  } finally {
    rmSync(container, { recursive: true, force: true });
  }
});
